# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [2]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [16]:
A = np.arange(1, 16).reshape(3,5)

In [7]:
print(A.ndim)
print(A.shape)
print(A.size)
print(type(A))

2
(3, 5)
15
<class 'numpy.ndarray'>


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [8]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


Element wise subtraction (B-C)

In [12]:
subtract_result = B - C
print(subtract_result)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]


Element wise multiplication (B . C)

In [16]:
mult_result = B * C
print(mult_result)

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]


Matrix multiplication

In [17]:
matrix_mult_result = B @ C
print(matrix_mult_result)

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [2]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
exp_result = np.exp(B)
print(f"exp_result = {exp_result}")
min_result = np.min(B)
print(f"min_result = {min_result}")

min_each_row_result = np.array([0, 0, 0])

for i, row in enumerate(B):
    min_each_row_result[i] = np.min(row)
print(f"min_each_row-result = {min_each_row_result}")
print(f"inx_of_each_row = {np.argmin(min_each_row_result)}")


min_each_col_result = np.array([0, 0, 0])

for i in range(B.shape[1]):
    min_each_col_result[i] = np.min(B[:, i])
    
print(f"min_each_col_result = {min_each_col_result}")


print(f"inx_val_of_min_val=  {np.argmin(B)}")

print(f"sum_of_all_elements=  {np.sum(B)}")

print(f"mean_of_first_col=  {np.mean(B[:, 0])}")
print(f"mean_of_second_col=  {np.mean(B[:, 1])}")
print(f"mean_of_third_col=  {np.mean(B[:, 2])}")

print(f"median_of_first_col=  {np.median(B[:, 0])}")
print(f"median_of_second_col=  {np.median(B[:, 1])}")
print(f"median_of_third_col=  {np.median(B[:, 2])}")





exp_result = [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
min_result = 1
min_each_row-result = [1 4 7]
inx_of_each_row = 0
min_each_col_result = [1 2 3]
inx_val_of_min_val=  0
sum_of_all_elements=  45
mean_of_first_col=  4.0
mean_of_second_col=  5.0
mean_of_third_col=  6.0
median_of_first_col=  4.0
median_of_second_col=  5.0
median_of_third_col=  6.0


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [17]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [18]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

It means that we put the first axis which is rows and in this case is 1 so we are pointing the second row and since we do not specified 
any column so it should include the elements from all columns that exists in the row 1 (second row)

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [ ]:
A

In [21]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [20]:
for row in A:
    for el in row:
        print(el)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [33]:
a = np.arange(30)
b = a.reshape(2, 3, -1)
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


Answer:
b array is 3 dimensional array and this means that we have one matrix/array that has two items. Each item has 3 rows and each of those rows has 5 element. 
item 1 : [[ 0  1  2  3  4]
          [ 5  6  7  8  9]
          [10 11 12 13 14]]

item 2:  [[15 16 17 18 19]
          [20 21 22 23 24]
          [25 26 27 28 29]]

each item has 3 rows.
each of those rows has 5 elements

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [34]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [35]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [36]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [56]:
def add_mult_func(matrix1, matrix2, operation):
    if not isinstance(matrix1, np.ndarray) or not isinstance(matrix2, np.ndarray):
        print("The inputs must be numpy.ndarray")
    
    if operation not in ["add", "multiply"]:
        print("The inputs must be numpy.ndarray")
    
    if operation == "add":
        if matrix1.shape != matrix2.shape:
            print("Both matrixes should have the same shape")
        else:
            print(matrix1 + matrix2) 
        
    if operation == "multiply":
        if matrix1.shape[1] != matrix2.shape[0]:
            print("the number of columns in the first matrix should be equal to the number of rows in the second matrix")
        else:
            print(np.dot(matrix1, matrix2))
    
    
            
m1 = np.array([[1, 2, 3], [4, 5, 6]])
m2 = np.array([[7, 8, 9], [10, 11, 12]])

add_mult_func(m1, m2, "add")

[[ 8 10 12]
 [14 16 18]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [3]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [4]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [5]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [10]:
def check_if_array_veiw_or_copy(vec1, vec2):
    if vec2.base is not vec1:
        print(f"{vec2} is a copy of {vec1}")
    else:
        print(f"{vec2} is a veiw of {vec1}")
        
check_if_array_veiw_or_copy(v1, v2)
print(v1)
print(v2)

#the last element in v1 will be changes too because v2 is a view of v1 so v1 as the base vill be changed.
        
        

[  2 123] is a veiw of [  0   1   2 123]
[  0   1   2 123]
[  2 123]
